/**
 * Mapper pour associer les noms de marques aux logos locaux
 * dans assets/optimized
 */

// Import de tous les logos disponibles
const brandLogos: Record<string, any> = {
  '9ff': require('@/assets/optimized/9ff.png'),
  'abadal': require('@/assets/optimized/abadal.png'),
  'abarth': require('@/assets/optimized/abarth.png'),
  'abbott-detroit': require('@/assets/optimized/abbott-detroit.png'),
  'abt': require('@/assets/optimized/abt.png'),
  'ac': require('@/assets/optimized/ac.png'),
  'acura': require('@/assets/optimized/acura.png'),
  'aiways': require('@/assets/optimized/aiways.png'),
  'aixam': require('@/assets/optimized/aixam.png'),
  'alfa-romeo': require('@/assets/optimized/alfa-romeo.png'),
  'alpina': require('@/assets/optimized/alpina.png'),
  'alpine': require('@/assets/optimized/alpine.png'),
  'alta': require('@/assets/optimized/alta.png'),
  'alvis': require('@/assets/optimized/alvis.png'),
  'amc': require('@/assets/optimized/amc.png'),
  'apollo': require('@/assets/optimized/apollo.png'),
  'arash': require('@/assets/optimized/arash.png'),
  'arcfox': require('@/assets/optimized/arcfox.png'),
  'ariel': require('@/assets/optimized/ariel.png'),
  'aro': require('@/assets/optimized/aro.png'),
  'arrinera': require('@/assets/optimized/arrinera.png'),
  'arrival': require('@/assets/optimized/arrival.png'),
  'artega': require('@/assets/optimized/artega.png'),
  'ascari': require('@/assets/optimized/ascari.png'),
  'askam': require('@/assets/optimized/askam.png'),
  'aspark': require('@/assets/optimized/aspark.png'),
  'aston-martin': require('@/assets/optimized/aston-martin.png'),
  'atalanta': require('@/assets/optimized/atalanta.png'),
  'auburn': require('@/assets/optimized/auburn.png'),
  'audi': require('@/assets/optimized/audi.png'),
  'audi-sport': require('@/assets/optimized/audi-sport.png'),
  'austin': require('@/assets/optimized/austin.png'),
  'autobacs': require('@/assets/optimized/autobacs.png'),
  'autobianchi': require('@/assets/optimized/autobianchi.png'),
  'axon': require('@/assets/optimized/axon.png'),
  'bac': require('@/assets/optimized/bac.png'),
  'baic-motor': require('@/assets/optimized/baic-motor.png'),
  'baojun': require('@/assets/optimized/baojun.png'),
  'beiben': require('@/assets/optimized/beiben.png'),
  'bentley': require('@/assets/optimized/bentley.png'),
  'berkeley': require('@/assets/optimized/berkeley.png'),
  'berliet': require('@/assets/optimized/berliet.png'),
  'bertone': require('@/assets/optimized/bertone.png'),
  'bestune': require('@/assets/optimized/bestune.png'),
  'bharatbenz': require('@/assets/optimized/bharatbenz.png'),
  'bitter': require('@/assets/optimized/bitter.png'),
  'bizzarrini': require('@/assets/optimized/bizzarrini.png'),
  'bmw': require('@/assets/optimized/bmw.png'),
  'bmw-m': require('@/assets/optimized/bmw-m.png'),
  'borgward': require('@/assets/optimized/borgward.png'),
  'bowler': require('@/assets/optimized/bowler.png'),
  'brabus': require('@/assets/optimized/brabus.png'),
  'brammo': require('@/assets/optimized/brammo.png'),
  'brilliance': require('@/assets/optimized/brilliance.png'),
  'bristol': require('@/assets/optimized/bristol.png'),
  'brooke': require('@/assets/optimized/brooke.png'),
  'bufori': require('@/assets/optimized/bufori.png'),
  'bugatti': require('@/assets/optimized/bugatti.png'),
  'buick': require('@/assets/optimized/buick.png'),
  'byd': require('@/assets/optimized/byd.png'),
  'byton': require('@/assets/optimized/byton.png'),
  'cadillac': require('@/assets/optimized/cadillac.png'),
  'camc': require('@/assets/optimized/camc.png'),
  'canoo': require('@/assets/optimized/canoo.png'),
  'caparo': require('@/assets/optimized/caparo.png'),
  'carlsson': require('@/assets/optimized/carlsson.png'),
  'caterham': require('@/assets/optimized/caterham.png'),
  'changan': require('@/assets/optimized/changan.png'),
  'changfeng': require('@/assets/optimized/changfeng.png'),
  'chery': require('@/assets/optimized/chery.png'),
  'chevrolet': require('@/assets/optimized/chevrolet.png'),
  'chevrolet-corvette': require('@/assets/optimized/chevrolet-corvette.png'),
  'chrysler': require('@/assets/optimized/chrysler.png'),
  'cisitalia': require('@/assets/optimized/cisitalia.png'),
  'citroen': require('@/assets/optimized/citroen.png'),
  'cizeta': require('@/assets/optimized/cizeta.png'),
  'cole': require('@/assets/optimized/cole.png'),
  'corre-la-licorne': require('@/assets/optimized/corre-la-licorne.png'),
  'cupra': require('@/assets/optimized/cupra.png'),
  'dacia': require('@/assets/optimized/dacia.png'),
  'daewoo': require('@/assets/optimized/daewoo.png'),
  'daf': require('@/assets/optimized/daf.png'),
  'daihatsu': require('@/assets/optimized/daihatsu.png'),
  'daimler': require('@/assets/optimized/daimler.png'),
  'dartz': require('@/assets/optimized/dartz.png'),
  'datsun': require('@/assets/optimized/datsun.png'),
  'david-brown': require('@/assets/optimized/david-brown.png'),
  'dayun': require('@/assets/optimized/dayun.png'),
  'de-tomaso': require('@/assets/optimized/de-tomaso.png'),
  'delage': require('@/assets/optimized/delage.png'),
  'desoto': require('@/assets/optimized/desoto.png'),
  'detroit-electric': require('@/assets/optimized/detroit-electric.png'),
  'devel-sixteen': require('@/assets/optimized/devel-sixteen.png'),
  'diatto': require('@/assets/optimized/diatto.png'),
  'dina': require('@/assets/optimized/dina.png'),
  'dkw': require('@/assets/optimized/dkw.png'),
  'dmc': require('@/assets/optimized/dmc.png'),
  'dodge': require('@/assets/optimized/dodge.png'),
  'dodge-viper': require('@/assets/optimized/dodge-viper.png'),
  'dongfeng': require('@/assets/optimized/dongfeng.png'),
  'donkervoort': require('@/assets/optimized/donkervoort.png'),
  'drako': require('@/assets/optimized/drako.png'),
  'ds': require('@/assets/optimized/ds.png'),
  'duesenberg': require('@/assets/optimized/duesenberg.png'),
  'eagle': require('@/assets/optimized/eagle.png'),
  'edag': require('@/assets/optimized/edag.png'),
  'edsel': require('@/assets/optimized/edsel.png'),
  'eicher': require('@/assets/optimized/eicher.png'),
  'elemental': require('@/assets/optimized/elemental.png'),
  'elfin': require('@/assets/optimized/elfin.png'),
  'elva': require('@/assets/optimized/elva.png'),
  'englon': require('@/assets/optimized/englon.png'),
  'erf': require('@/assets/optimized/erf.png'),
  'eterniti': require('@/assets/optimized/eterniti.png'),
  'exeed': require('@/assets/optimized/exeed.png'),
  'facel-vega': require('@/assets/optimized/facel-vega.png'),
  'faraday-future': require('@/assets/optimized/faraday-future.png'),
  'faw': require('@/assets/optimized/faw.png'),
  'faw-jiefang': require('@/assets/optimized/faw-jiefang.png'),
  'ferrari': require('@/assets/optimized/ferrari.png'),
  'fiat': require('@/assets/optimized/fiat.png'),
  'fioravanti': require('@/assets/optimized/fioravanti.png'),
  'fisker': require('@/assets/optimized/fisker.png'),
  'foden': require('@/assets/optimized/foden.png'),
  'force-motors': require('@/assets/optimized/force-motors.png'),
  'ford': require('@/assets/optimized/ford.png'),
  'ford-mustang': require('@/assets/optimized/ford-mustang.png'),
  'foton': require('@/assets/optimized/foton.png'),
  'fpv': require('@/assets/optimized/fpv.png'),
  'franklin': require('@/assets/optimized/franklin.png'),
  'freightliner': require('@/assets/optimized/freightliner.png'),
  'fso': require('@/assets/optimized/fso.png'),
  'gac-group': require('@/assets/optimized/gac-group.png'),
  'gardner-douglas': require('@/assets/optimized/gardner-douglas.png'),
  'gaz': require('@/assets/optimized/gaz.png'),
  'geely': require('@/assets/optimized/geely.png'),
  'general-motors': require('@/assets/optimized/general-motors.png'),
  'genesis': require('@/assets/optimized/genesis.png'),
  'geo': require('@/assets/optimized/geo.png'),
  'geometry': require('@/assets/optimized/geometry.png'),
  'gilbern': require('@/assets/optimized/gilbern.png'),
  'gillet': require('@/assets/optimized/gillet.png'),
  'ginetta': require('@/assets/optimized/ginetta.png'),
  'gmc': require('@/assets/optimized/gmc.png'),
  'golden-dragon': require('@/assets/optimized/golden-dragon.png'),
  'gonow': require('@/assets/optimized/gonow.png'),
  'great-wall': require('@/assets/optimized/great-wall.png'),
  'grinnall': require('@/assets/optimized/grinnall.png'),
  'gumpert': require('@/assets/optimized/gumpert.png'),
  'hafei': require('@/assets/optimized/hafei.png'),
  'haima': require('@/assets/optimized/haima.png'),
  'haval': require('@/assets/optimized/haval.png'),
  'hawtai': require('@/assets/optimized/hawtai.png'),
  'hennessey': require('@/assets/optimized/hennessey.png'),
  'higer': require('@/assets/optimized/higer.png'),
  'hillman': require('@/assets/optimized/hillman.png'),
  'hindustan-motors': require('@/assets/optimized/hindustan-motors.png'),
  'hino': require('@/assets/optimized/hino.png'),
  'hiphi': require('@/assets/optimized/hiphi.png'),
  'hispano-suiza': require('@/assets/optimized/hispano-suiza.png'),
  'holden': require('@/assets/optimized/holden.png'),
  'hommell': require('@/assets/optimized/hommell.png'),
  'honda': require('@/assets/optimized/honda.png'),
  'hongqi': require('@/assets/optimized/hongqi.png'),
  'hongyan': require('@/assets/optimized/hongyan.png'),
  'horch': require('@/assets/optimized/horch.png'),
  'hsv': require('@/assets/optimized/hsv.png'),
  'hudson': require('@/assets/optimized/hudson.png'),
  'hummer': require('@/assets/optimized/hummer.png'),
  'hupmobile': require('@/assets/optimized/hupmobile.png'),
  'hyundai': require('@/assets/optimized/hyundai.png'),
  'ic-bus': require('@/assets/optimized/ic-bus.png'),
  'ih': require('@/assets/optimized/ih.png'),
  'ikco': require('@/assets/optimized/ikco.png'),
  'infiniti': require('@/assets/optimized/infiniti.png'),
  'innocenti': require('@/assets/optimized/innocenti.png'),
  'intermeccanica': require('@/assets/optimized/intermeccanica.png'),
  'international': require('@/assets/optimized/international.png'),
  'irizar': require('@/assets/optimized/irizar.png'),
  'isdera': require('@/assets/optimized/isdera.png'),
  'iso': require('@/assets/optimized/iso.png'),
  'isuzu': require('@/assets/optimized/isuzu.png'),
  'iveco': require('@/assets/optimized/iveco.png'),
  'jac': require('@/assets/optimized/jac.png'),
  'jaguar': require('@/assets/optimized/jaguar.png'),
  'jawa': require('@/assets/optimized/jawa.png'),
  'jba-motors': require('@/assets/optimized/jba-motors.png'),
  'jeep': require('@/assets/optimized/jeep.png'),
  'jensen': require('@/assets/optimized/jensen.png'),
  'jetour': require('@/assets/optimized/jetour.png'),
  'jetta': require('@/assets/optimized/jetta.png'),
  'jmc': require('@/assets/optimized/jmc.png'),
  'kaiser': require('@/assets/optimized/kaiser.png'),
  'kamaz': require('@/assets/optimized/kamaz.png'),
  'karlmann-king': require('@/assets/optimized/karlmann-king.png'),
  'karma': require('@/assets/optimized/karma.png'),
  'keating': require('@/assets/optimized/keating.png'),
  'kenworth': require('@/assets/optimized/kenworth.png'),
  'kia': require('@/assets/optimized/kia.png'),
  'king-long': require('@/assets/optimized/king-long.png'),
  'koenigsegg': require('@/assets/optimized/koenigsegg.png'),
  'ktm': require('@/assets/optimized/ktm.png'),
  'lada': require('@/assets/optimized/lada.png'),
  'lagonda': require('@/assets/optimized/lagonda.png'),
  'lamborghini': require('@/assets/optimized/lamborghini.png'),
  'lancia': require('@/assets/optimized/lancia.png'),
  'land-rover': require('@/assets/optimized/land-rover.png'),
  'landwind': require('@/assets/optimized/landwind.png'),
  'laraki': require('@/assets/optimized/laraki.png'),
  'leapmotor': require('@/assets/optimized/leapmotor.png'),
  'levc': require('@/assets/optimized/levc.png'),
  'lexus': require('@/assets/optimized/lexus.png'),
  'leyland': require('@/assets/optimized/leyland.png'),
  'li-auto': require('@/assets/optimized/li-auto.png'),
  'lifan': require('@/assets/optimized/lifan.png'),
  'ligier': require('@/assets/optimized/ligier.png'),
  'lincoln': require('@/assets/optimized/lincoln.png'),
  'lister': require('@/assets/optimized/lister.png'),
  'lloyd': require('@/assets/optimized/lloyd.png'),
  'lobini': require('@/assets/optimized/lobini.png'),
  'lordstown': require('@/assets/optimized/lordstown.png'),
  'lotus': require('@/assets/optimized/lotus.png'),
  'lucid': require('@/assets/optimized/lucid.png'),
  'luxgen': require('@/assets/optimized/luxgen.png'),
  'lynk-and-co': require('@/assets/optimized/lynk-and-co.png'),
  'mack': require('@/assets/optimized/mack.png'),
  'mahindra': require('@/assets/optimized/mahindra.png'),
  'man': require('@/assets/optimized/man.png'),
  'mansory': require('@/assets/optimized/mansory.png'),
  'marcos': require('@/assets/optimized/marcos.png'),
  'marlin': require('@/assets/optimized/marlin.png'),
  'maserati': require('@/assets/optimized/maserati.png'),
  'mastretta': require('@/assets/optimized/mastretta.png'),
  'maxus': require('@/assets/optimized/maxus.png'),
  'maybach': require('@/assets/optimized/maybach.png'),
  'maz': require('@/assets/optimized/maz.png'),
  'mazda': require('@/assets/optimized/mazda.png'),
  'mazzanti': require('@/assets/optimized/mazzanti.png'),
  'mclaren': require('@/assets/optimized/mclaren.png'),
  'melkus': require('@/assets/optimized/melkus.png'),
  'mercedes-amg': require('@/assets/optimized/mercedes-amg.png'),
  'mercedes-benz': require('@/assets/optimized/mercedes-benz.png'),
  'mercury': require('@/assets/optimized/mercury.png'),
  'merkur': require('@/assets/optimized/merkur.png'),
  'mev': require('@/assets/optimized/mev.png'),
  'mg': require('@/assets/optimized/mg.png'),
  'microcar': require('@/assets/optimized/microcar.png'),
  'mini': require('@/assets/optimized/mini.png'),
  'mitsubishi': require('@/assets/optimized/mitsubishi.png'),
  'mitsuoka': require('@/assets/optimized/mitsuoka.png'),
  'mk': require('@/assets/optimized/mk.png'),
  'morgan': require('@/assets/optimized/morgan.png'),
  'morris': require('@/assets/optimized/morris.png'),
  'mosler': require('@/assets/optimized/mosler.png'),
  'navistar': require('@/assets/optimized/navistar.png'),
  'nevs': require('@/assets/optimized/nevs.png'),
  'nikola': require('@/assets/optimized/nikola.png'),
  'nio': require('@/assets/optimized/nio.png'),
  'nissan': require('@/assets/optimized/nissan.png'),
  'nissan-gt-r': require('@/assets/optimized/nissan-gt-r.png'),
  'nissan-nismo': require('@/assets/optimized/nissan-nismo.png'),
  'noble': require('@/assets/optimized/noble.png'),
  'oldsmobile': require('@/assets/optimized/oldsmobile.png'),
  'oltcit': require('@/assets/optimized/oltcit.png'),
  'omoda': require('@/assets/optimized/omoda.png'),
  'opel': require('@/assets/optimized/opel.png'),
  'osca': require('@/assets/optimized/osca.png'),
  'paccar': require('@/assets/optimized/paccar.png'),
  'packard': require('@/assets/optimized/packard.png'),
  'pagani': require('@/assets/optimized/pagani.png'),
  'panhard': require('@/assets/optimized/panhard.png'),
  'panoz': require('@/assets/optimized/panoz.png'),
  'pegaso': require('@/assets/optimized/pegaso.png'),
  'perodua': require('@/assets/optimized/perodua.png'),
  'peterbilt': require('@/assets/optimized/peterbilt.png'),
  'peugeot': require('@/assets/optimized/peugeot.png'),
  'pgo': require('@/assets/optimized/pgo.png'),
  'pierce-arrow': require('@/assets/optimized/pierce-arrow.png'),
  'pininfarina': require('@/assets/optimized/pininfarina.png'),
  'plymouth': require('@/assets/optimized/plymouth.png'),
  'polestar': require('@/assets/optimized/polestar.png'),
  'pontiac': require('@/assets/optimized/pontiac.png'),
  'porsche': require('@/assets/optimized/porsche.png'),
  'praga': require('@/assets/optimized/praga.png'),
  'premier': require('@/assets/optimized/premier.png'),
  'prodrive': require('@/assets/optimized/prodrive.png'),
  'proton': require('@/assets/optimized/proton.png'),
  'qoros': require('@/assets/optimized/qoros.png'),
  'radical': require('@/assets/optimized/radical.png'),
  'ram': require('@/assets/optimized/ram.png'),
  'rambler': require('@/assets/optimized/rambler.png'),
  'ranz': require('@/assets/optimized/ranz.png'),
  'renault': require('@/assets/optimized/renault.png'),
  'renault-samsung': require('@/assets/optimized/renault-samsung.png'),
  'rezvani': require('@/assets/optimized/rezvani.png'),
  'riley': require('@/assets/optimized/riley.png'),
  'rimac': require('@/assets/optimized/rimac.png'),
  'rinspeed': require('@/assets/optimized/rinspeed.png'),
  'rivian': require('@/assets/optimized/rivian.png'),
  'roewe': require('@/assets/optimized/roewe.png'),
  'rolls-royce': require('@/assets/optimized/rolls-royce.png'),
  'ronart': require('@/assets/optimized/ronart.png'),
  'rossion': require('@/assets/optimized/rossion.png'),
  'rover': require('@/assets/optimized/rover.png'),
  'ruf': require('@/assets/optimized/ruf.png'),
  'saab': require('@/assets/optimized/saab.png'),
  'saic-motor': require('@/assets/optimized/saic-motor.png'),
  'saipa': require('@/assets/optimized/saipa.png'),
  'saleen': require('@/assets/optimized/saleen.png'),
  'saturn': require('@/assets/optimized/saturn.png'),
  'scania': require('@/assets/optimized/scania.png'),
  'scion': require('@/assets/optimized/scion.png'),
  'seat': require('@/assets/optimized/seat.png'),
  'setra': require('@/assets/optimized/setra.png'),
  'sev': require('@/assets/optimized/sev.png'),
  'shacman': require('@/assets/optimized/shacman.png'),
  'simca': require('@/assets/optimized/simca.png'),
  'singer': require('@/assets/optimized/singer.png'),
  'singulato': require('@/assets/optimized/singulato.png'),
  'sinotruk': require('@/assets/optimized/sinotruk.png'),
  'sisu': require('@/assets/optimized/sisu.png'),
  'skoda': require('@/assets/optimized/skoda.png'),
  'smart': require('@/assets/optimized/smart.png'),
  'soueast': require('@/assets/optimized/soueast.png'),
  'spania-gta': require('@/assets/optimized/spania-gta.png'),
  'spirra': require('@/assets/optimized/spirra.png'),
  'spyker': require('@/assets/optimized/spyker.png'),
  'ssangyong': require('@/assets/optimized/ssangyong.png'),
  'ssc': require('@/assets/optimized/ssc.png'),
  'sterling': require('@/assets/optimized/sterling.png'),
  'studebaker': require('@/assets/optimized/studebaker.png'),
  'stutz': require('@/assets/optimized/stutz.png'),
  'subaru': require('@/assets/optimized/subaru.png'),
  'suffolk': require('@/assets/optimized/suffolk.png'),
  'suzuki': require('@/assets/optimized/suzuki.png'),
  'talbot': require('@/assets/optimized/talbot.png'),
  'tata': require('@/assets/optimized/tata.png'),
  'tatra': require('@/assets/optimized/tatra.png'),
  'tauro': require('@/assets/optimized/tauro.png'),
  'techart': require('@/assets/optimized/techart.png'),
  'tesla': require('@/assets/optimized/tesla.png'),
  'toyota': require('@/assets/optimized/toyota.png'),
  'toyota-alphard': require('@/assets/optimized/toyota-alphard.png'),
  'toyota-century': require('@/assets/optimized/toyota-century.png'),
  'toyota-crown': require('@/assets/optimized/toyota-crown.png'),
  'tramontana': require('@/assets/optimized/tramontana.png'),
  'trion': require('@/assets/optimized/trion.png'),
  'triumph': require('@/assets/optimized/triumph.png'),
  'troller': require('@/assets/optimized/troller.png'),
  'tucker': require('@/assets/optimized/tucker.png'),
  'tvr': require('@/assets/optimized/tvr.png'),
  'uaz': require('@/assets/optimized/uaz.png'),
  'ud': require('@/assets/optimized/ud.png'),
  'ultima': require('@/assets/optimized/ultima.png'),
  'vandenbrink': require('@/assets/optimized/vandenbrink.png'),
  'vauxhall': require('@/assets/optimized/vauxhall.png'),
  'vector': require('@/assets/optimized/vector.png'),
  'vencer': require('@/assets/optimized/vencer.png'),
  'venturi': require('@/assets/optimized/venturi.png'),
  'venucia': require('@/assets/optimized/venucia.png'),
  'vinfast': require('@/assets/optimized/vinfast.png'),
  'vlf': require('@/assets/optimized/vlf.png'),
  'volkswagen': require('@/assets/optimized/volkswagen.png'),
  'volvo': require('@/assets/optimized/volvo.png'),
  'w-motors': require('@/assets/optimized/w-motors.png'),
  'wanderer': require('@/assets/optimized/wanderer.png'),
  'wartburg': require('@/assets/optimized/wartburg.png'),
  'weltmeister': require('@/assets/optimized/weltmeister.png'),
  'western-star': require('@/assets/optimized/western-star.png'),
  'westfield': require('@/assets/optimized/westfield.png'),
  'wey': require('@/assets/optimized/wey.png'),
  'wiesmann': require('@/assets/optimized/wiesmann.png'),
  'willys-overland': require('@/assets/optimized/willys-overland.png'),
  'workhorse': require('@/assets/optimized/workhorse.png'),
  'wuling': require('@/assets/optimized/wuling.png'),
  'xpeng': require('@/assets/optimized/xpeng.png'),
  'yulon': require('@/assets/optimized/yulon.png'),
  'yutong': require('@/assets/optimized/yutong.png'),
  'zarooq-motors': require('@/assets/optimized/zarooq-motors.png'),
  'zastava': require('@/assets/optimized/zastava.png'),
  'zaz': require('@/assets/optimized/zaz.png'),
  'zeekr': require('@/assets/optimized/zeekr.png'),
  'zenos': require('@/assets/optimized/zenos.png'),
  'zenvo': require('@/assets/optimized/zenvo.png'),
  'zhongtong': require('@/assets/optimized/zhongtong.png'),
  'zinoro': require('@/assets/optimized/zinoro.png'),
  'zotye': require('@/assets/optimized/zotye.png'),
};

// Mapping des variations de noms de marques vers les noms de fichiers
const brandNameMapping: Record<string, string> = {
  // Variations courantes
  'mercedes': 'mercedes-benz',
  'mercedes benz': 'mercedes-benz',
  'mercedes-benz': 'mercedes-benz',
  'bmw': 'bmw',
  'renault': 'renault',
  'peugeot': 'peugeot',
  'citroen': 'citroen',
  'citroën': 'citroen',
  'volkswagen': 'volkswagen',
  'vw': 'volkswagen',
  'audi': 'audi',
  'ford': 'ford',
  'opel': 'opel',
  'fiat': 'fiat',
  'toyota': 'toyota',
  'nissan': 'nissan',
  'honda': 'honda',
  'hyundai': 'hyundai',
  'kia': 'kia',
  'mazda': 'mazda',
  'suzuki': 'suzuki',
  'mitsubishi': 'mitsubishi',
  'subaru': 'subaru',
  'lexus': 'lexus',
  'infiniti': 'infiniti',
  'acura': 'acura',
  'volvo': 'volvo',
  'saab': 'saab',
  'jaguar': 'jaguar',
  'land rover': 'land-rover',
  'landrover': 'land-rover',
  'range rover': 'land-rover',
  'porsche': 'porsche',
  'ferrari': 'ferrari',
  'lamborghini': 'lamborghini',
  'maserati': 'maserati',
  'bentley': 'bentley',
  'rolls royce': 'rolls-royce',
  'rolls-royce': 'rolls-royce',
  'aston martin': 'aston-martin',
  'aston-martin': 'aston-martin',
  'mclaren': 'mclaren',
  'bugatti': 'bugatti',
  'tesla': 'tesla',
  'dacia': 'dacia',
  'seat': 'seat',
  'skoda': 'skoda',
  'alfa romeo': 'alfa-romeo',
  'alfaromeo': 'alfa-romeo',
  'alfa-romeo': 'alfa-romeo',
  'lancia': 'lancia',
  'mini': 'mini',
  'smart': 'smart',
  'ds': 'ds',
  'cupra': 'cupra',
  'genesis': 'genesis',
  'polestar': 'polestar',
  'rivian': 'rivian',
  'lucid': 'lucid',
  'nio': 'nio',
  'xpeng': 'xpeng',
  'byd': 'byd',
  'geely': 'geely',
  'great wall': 'great-wall',
  'greatwall': 'great-wall',
  'great-wall': 'great-wall',
  'haval': 'haval',
  'wey': 'wey',
  'lynk and co': 'lynk-and-co',
  'lynk-and-co': 'lynk-and-co',
  'zeekr': 'zeekr',
  'mg': 'mg',
  'roewe': 'roewe',
  'maxus': 'maxus',
  'isuzu': 'isuzu',
  'maz': 'maz',
  'gmc': 'gmc',
  'chevrolet': 'chevrolet',
  'cadillac': 'cadillac',
  'buick': 'buick',
  'chrysler': 'chrysler',
  'dodge': 'dodge',
  'jeep': 'jeep',
  'ram': 'ram',
  'lincoln': 'lincoln',
  'ford mustang': 'ford-mustang',
  'ford-mustang': 'ford-mustang',
  'dodge viper': 'dodge-viper',
  'dodge-viper': 'dodge-viper',
  'chevrolet corvette': 'chevrolet-corvette',
  'chevrolet-corvette': 'chevrolet-corvette',
};

/**
 * Normalise un nom de marque pour le mapper vers un fichier logo
 */
function normalizeBrandName(brandName: string): string {
  if (!brandName) return '';
  
  // Convertir en minuscules et supprimer les espaces en début/fin
  let normalized = brandName.toLowerCase().trim();
  
  // Remplacer les espaces multiples par un seul espace
  normalized = normalized.replace(/\s+/g, ' ');
  
  // Vérifier d'abord dans le mapping
  if (brandNameMapping[normalized]) {
    return brandNameMapping[normalized];
  }
  
  // Sinon, remplacer les espaces par des tirets et supprimer les caractères spéciaux
  normalized = normalized
    .replace(/\s+/g, '-')
    .replace(/[^a-z0-9-]/g, '')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');
  
  return normalized;
}

/**
 * Normalise un nom de marque pour le stockage (format "local:xxx")
 * Utilisé pour stocker l'identifiant du logo local dans la base de données
 */
export function normalizeBrandNameForStorage(brandName: string): string {
  const normalized = normalizeBrandName(brandName);
  return normalized ? `local:${normalized}` : '';
}

/**
 * Récupère le logo d'une marque depuis les assets locaux
 * @param brandName - Nom de la marque (ex: "Renault", "Mercedes-Benz", etc.)
 * @returns Le require() du logo ou undefined si non trouvé
 */
export function getBrandLogo(brandName: string): any {
  if (!brandName || brandName.trim() === '') {
    return undefined;
  }

  const normalizedBrand = normalizeBrandName(brandName);
  
  if (!normalizedBrand) {
    return undefined;
  }

  // Retourner le logo depuis le mapping statique
  const logo = brandLogos[normalizedBrand];
  
  if (logo) {
    console.log(`✅ Logo trouvé pour la marque: ${brandName} (normalisé: ${normalizedBrand})`);
    return logo;
  } else {
    console.warn(`⚠️ Logo non trouvé pour la marque: ${brandName} (normalisé: ${normalizedBrand})`);
    return undefined;
  }
}

/**
 * Vérifie si un logo existe pour une marque donnée
 */
export function hasBrandLogo(brandName: string): boolean {
  return getBrandLogo(brandName) !== undefined;
}
